Repository whamcloud/lustrefs-exporter, pull requests merged in 2024-08, with the labels that each got.

#66 Switch server to axum
  Cargo.lock
  Cargo.toml
  lustre-collector/src/types.rs
  lustrefs-exporter/Cargo.toml
  lustrefs-exporter/src/main.rs
Labels: chore

#68 Switch jobstats to streaming impl
  .gitattributes
  .github/workflows/testing.yml
  .gitignore
  Cargo.lock
  Cargo.toml
  lustre-collector/Cargo.lock
  lustre-collector/src/fixtures/valid/ex8761-lctl.txt
  lustre-collector/src/fixtures/valid/lustre-2.14.0_ddn133/2.14.0_ddn133_exports.txt
  lustre-collector/src/fixtures/valid/lustre-2.14.0_ddn133/2.14.0_ddn133_quota.txt
  lustre-collector/src/fixtures/valid/lustre-2.14.0_ddn145/2.14.0_ddn145_stats.txt
  lustre-collector/src/fixtures/valid/params-6.2.0-r9.txt
  lustre-collector/src/fixtures/valid/valid.txt
  lustre-collector/src/fixtures/valid/valid2.txt
  lustre-collector/src/fixtures/valid/valid_mds.txt
  lustre-collector/src/fixtures/valid/valid_no_newline.txt
  lustre-collector/src/fixtures/valid/valid_unhealthy_host.txt
  lustre-collector/src/mds/job_stats.rs
  lustre-collector/src/mds/mdt_parser.rs
  lustre-collector/src/mds/mod.rs
  lustre-collector/src/oss/job_stats.rs
  lustre-collector/src/oss/mod.rs
  lustre-collector/src/oss/obdfilter_parser.rs
  lustre-collector/src/snapshots/lustre_collector__parser__tests__params.snap
  lustre-collector/src/snapshots/lustre_collector__parser__tests__valid_fixture_ex8761-lctl.txt.snap
  lustre-collector/src/snapshots/lustre_collector__parser__tests__valid_fixture_lustre-2.14.0_ddn133__2.14.0_ddn133_exports.txt.snap
  lustre-collector/src/snapshots/lustre_collector__parser__tests__valid_fixture_lustre-2.14.0_ddn133__2.14.0_ddn133_quota.txt.snap
  lustre-collector/src/snapshots/lustre_collector__parser__tests__valid_fixture_lustre-2.14.0_ddn145__2.14.0_ddn145_stats.txt.snap
  lustre-collector/src/snapshots/lustre_collector__parser__tests__valid_fixture_params-6.2.0-r9.txt.snap
  lustre-collector/src/snapshots/lustre_collector__parser__tests__valid_fixture_valid.txt.snap
  lustre-collector/src/snapshots/lustre_collector__parser__tests__valid_fixture_valid2.txt.snap
  lustre-collector/src/snapshots/lustre_collector__parser__tests__valid_fixture_valid_mds.txt.snap
  lustre-collector/src/snapshots/lustre_collector__parser__tests__valid_fixture_valid_no_newline.txt.snap
  lustre-collector/src/snapshots/lustre_collector__parser__tests__valid_fixture_valid_unhealthy_host.txt.snap
  lustre-collector/src/snapshots/lustre_collector__tests__params.snap
  lustre-collector/src/types.rs
  lustrefs-exporter/Cargo.lock
  lustrefs-exporter/Cargo.toml
  lustrefs-exporter/fixtures/host_stats_non_healthy.json
  lustrefs-exporter/fixtures/jobstats.json
  lustrefs-exporter/fixtures/jobstats_only/co-vm03.txt
  lustrefs-exporter/fixtures/jobstats_only/ds86.txt
  lustrefs-exporter/fixtures/lnetctl_stats.json
  lustrefs-exporter/fixtures/stats.json
  lustrefs-exporter/fixtures/stats_mds.json
  lustrefs-exporter/src/brw_stats.rs
  lustrefs-exporter/src/jobstats.rs
  lustrefs-exporter/src/lib.rs
  lustrefs-exporter/src/main.rs
  lustrefs-exporter/src/snapshots/lustrefs_exporter__tests__jobstats.snap
  lustrefs-exporter/src/snapshots/lustrefs_exporter__tests__valid_fixture_ex8761-lctl.txt.snap
  lustrefs-exporter/src/snapshots/lustrefs_exporter__tests__valid_fixture_params-6.2.0-r9.txt.snap
  lustrefs-exporter/src/snapshots/lustrefs_exporter__tests__valid_fixture_valid2.txt.snap
  rust-toolchain
Labels: enhancement

#73 Do not print error on jobstats issue
  lustrefs-exporter/src/main.rs
Labels: bug

#74 Bump to 0.9.1
  Cargo.lock
  Cargo.toml
  lustrefs-exporter/debian/changelog
  lustrefs-exporter/lustrefs_exporter.spec
Labels: chore

#76 Chain stream instead of merge
  Cargo.lock
  Cargo.toml
  lustrefs-exporter/debian/changelog
  lustrefs-exporter/fixtures/jobstats_only/2.14.0_164.txt
  lustrefs-exporter/lustrefs_exporter.spec
  lustrefs-exporter/src/jobstats.rs
  lustrefs-exporter/src/main.rs
  lustrefs-exporter/src/snapshots/lustrefs_exporter__jobstats__tests__parse_2_14_0_164_jobstats.snap
Labels: bug
