Repository whamcloud/lustrefs-exporter, pull requests merged in 2025-05, with the labels that each got.

#91 Update help message for 'lustre_health_healthy'
  lustrefs-exporter/src/host.rs
  lustrefs-exporter/src/main.rs
  lustrefs-exporter/src/snapshots/lustrefs_exporter__tests__client_stats_otel.snap
  lustrefs-exporter/src/snapshots/lustrefs_exporter__tests__host_stats_non_healthy_otel.snap
  lustrefs-exporter/src/snapshots/lustrefs_exporter__tests__lnetctl_stats_mds_otel.snap
  lustrefs-exporter/src/snapshots/lustrefs_exporter__tests__lnetctl_stats_otel.snap
  lustrefs-exporter/src/snapshots/lustrefs_exporter__tests__stats_otel.snap
  lustrefs-exporter/src/snapshots/lustrefs_exporter__tests__valid_fixture_otel_ex8761-lctl.txt.snap
  lustrefs-exporter/src/snapshots/lustrefs_exporter__tests__valid_fixture_otel_lustre-2-14-0__client__llite_client.txt.snap
  lustrefs-exporter/src/snapshots/lustrefs_exporter__tests__valid_fixture_otel_lustre-2.14.0_ddn133__2.14.0_ddn133_exports.txt.snap
  lustrefs-exporter/src/snapshots/lustrefs_exporter__tests__valid_fixture_otel_lustre-2.14.0_ddn133__2.14.0_ddn133_quota.txt.snap
  lustrefs-exporter/src/snapshots/lustrefs_exporter__tests__valid_fixture_otel_lustre-2.14.0_ddn145__2.14.0_ddn145_stats.txt.snap
  lustrefs-exporter/src/snapshots/lustrefs_exporter__tests__valid_fixture_otel_params-6.2.0-r9.txt.snap
  lustrefs-exporter/src/snapshots/lustrefs_exporter__tests__valid_fixture_otel_valid.txt.snap
  lustrefs-exporter/src/snapshots/lustrefs_exporter__tests__valid_fixture_otel_valid2.txt.snap
  lustrefs-exporter/src/snapshots/lustrefs_exporter__tests__valid_fixture_otel_valid_mds.txt.snap
  lustrefs-exporter/src/snapshots/lustrefs_exporter__tests__valid_fixture_otel_valid_no_newline.txt.snap
  lustrefs-exporter/src/snapshots/lustrefs_exporter__tests__valid_fixture_otel_valid_unhealthy_host.txt.snap
Labels: documentation

#93 Reduce log spam
  lustrefs-exporter/lustrefs_exporter.service
  lustrefs-exporter/src/lib.rs
Labels: bug

#96 Bump deps
  .taplo.toml
  Cargo.lock
  Cargo.toml
  lustre-collector/Cargo.toml
  lustre-collector/src/base_parsers.rs
  lustre-collector/src/brw_stats_parser.rs
  lustre-collector/src/exports_parser.rs
  lustre-collector/src/ldlm/ldlm_namespace_parser.rs
  lustre-collector/src/ldlm/ldlm_service_parser.rs
  lustre-collector/src/ldlm/mod.rs
  lustre-collector/src/lib.rs
  lustre-collector/src/llite/mod.rs
  lustre-collector/src/lnetctl_parser.rs
  lustre-collector/src/main.rs
  lustre-collector/src/mdd_parser.rs
  lustre-collector/src/mds/client_count_parser.rs
  lustre-collector/src/mds/mds_parser.rs
  lustre-collector/src/mds/mdt_parser.rs
  lustre-collector/src/mds/mod.rs
  lustre-collector/src/mgs/mgs_fs_parser.rs
  lustre-collector/src/mgs/mgs_parser.rs
  lustre-collector/src/node_stats_parsers.rs
  lustre-collector/src/osd_parser.rs
  lustre-collector/src/oss/mod.rs
  lustre-collector/src/oss/obdfilter_parser.rs
  lustre-collector/src/oss/oss_parser.rs
  lustre-collector/src/parser.rs
  lustre-collector/src/quota/mod.rs
  lustre-collector/src/quota/quota_parser.rs
  lustre-collector/src/recovery_status_parser.rs
  lustre-collector/src/stats_parser.rs
  lustre-collector/src/time.rs
  lustre-collector/src/top_level_parser.rs
  lustrefs-exporter/Cargo.toml
  lustrefs-exporter/benches/jobstats.rs
  lustrefs-exporter/src/brw_stats.rs
  lustrefs-exporter/src/host.rs
  lustrefs-exporter/src/jobstats.rs
  lustrefs-exporter/src/lib.rs
  lustrefs-exporter/src/llite.rs
  lustrefs-exporter/src/lnet.rs
  lustrefs-exporter/src/main.rs
  lustrefs-exporter/src/openmetrics.rs
  lustrefs-exporter/src/quota.rs
  lustrefs-exporter/src/service.rs
  lustrefs-exporter/src/stats.rs
  rust-toolchain
Labels: chore
